### ISSUE TITLE
padding-left and margin-left are not working

### ISSUE THREAD

**Issue by ashwinputhige** [givanz/VvvebJs#29]
padding-left and margin-left are not working. I think it's because they are defined with a capital L in `components-bootstrap.js` in 3 places.

```
    key: "padding-Left",
    key: "margin-Left",
```

**Comment by givanz** [comment]
Thanks for the bug report, the issue was with CssUnitInput, I fixed it in the last commit and I also changed key letter case.

**Comment by ashwinputhige** [comment]
Hi @givanz , Is the demo (http://www.vvveb.com/vvvebjs/editor.html) updated with this fix? Changing `Padding -> left` does not update the view.

**Comment by givanz** [comment]
I updated it now, browser clear cache might be needed for the changes to load.

**Comment by ashwinputhige** [comment]
Hi @givanz , I still don't see it :( .
To reproduce,
1. Go to http://www.vvveb.com/vvvebjs/editor.html
2. Click on the `div` surrounding Jumbotron
3. Change `padding-left`-> it does not update the `div`. `div class="jumbotron"` does not get the padding-left style.
4. Change `padding-right` -> `div` is updated as expected

**Comment by givanz** [comment]
Sorry, forgot to update components-bootstrap4.js to fix upper case "padding-Left", please check now.

**Comment by ashwinputhige** [comment]
Thanks
